spring.application.name=task-management-api

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/task_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
# update: automatically updates the database schema based on the @Entity classes
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries in the console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Default Server Port
server.port=8080
